spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate  # 실제 운영 환경에서는 validate 사용
    show-sql: true  # SQL 로그 출력
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    
logging:
  level:
    com.wanted.preonboarding_back: DEBUG
    org.hibernate.SQL: debug
    org.hibernate.type: trace  # SQL 쿼리의 파라미터 값 출력
    org.hibernate.orm.jdbc.bind: trace  # 바인딩되는 파라미터 값 출력

