spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/your_database
    username: your_username
    password: your_password
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate  # 실제 운영 환경에서는 validate 사용
    show-sql: true  # SQL 로그 출력
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false  # OSIV 비활성화
    
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace  # 바인딩되는 파라미터 값 출력